source $HYLUSTREMC/period_prefix.sh 
export hy_base_production_dir=$HYLUSTREMC/2008-11_Gener
export hy_base_production_period=2008-11
export hy_target_dir=/lustre/ihep.su/data/hyperon/HYPERON_MC/evdokimov/reconvert_from_$hy_base_production_period
export hy_base_anchors_dir=/lustre/ihep.su/data/hyperon/evdokimov_analysis
nfiles_per_thread=40


if mkdir -p $hy_target_dir ; then echo "$hy_target_dir exists." ; else echo "Cannot create $hy_target_dir. Stopping..."; return 1; fi
if cd $hy_target_dir ; then echo "..." ; else echo "Cannot cd into $hy_target_dir. Stopping..." ; return 1; fi
path_to_script=$(pwd)/$BASH_SOURCE
echo "This file was generated by script $path_to_script" >README  
echo "This is reconverted MC data using production stored in $hy_base_production_dir" >> README 
echo "Reconversion is done in $hy_target_dir for following periods: " >> README
list_periods >> $hy_target_dir/README
echo "I reconvert $nfiles_per_thread production files per thread." >> README



