/********************************************************************
* /afs/ihep.su/user/s/sevdokim/HyperonMC-factory/Hyp_RegGen/../tmp/tgt_linuxx8664gcc/HyperonMC_RegGen/HyperonMC_RegGenCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/ihep.su/user/s/sevdokim/HyperonMC-factory/Hyp_RegGen/../tmp/tgt_linuxx8664gcc/HyperonMC_RegGen/HyperonMC_RegGenCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHyperonMC_RegGenCint();
extern void G__cpp_setup_inheritanceHyperonMC_RegGenCint();
extern void G__cpp_setup_typetableHyperonMC_RegGenCint();
extern void G__cpp_setup_memvarHyperonMC_RegGenCint();
extern void G__cpp_setup_globalHyperonMC_RegGenCint();
extern void G__cpp_setup_memfuncHyperonMC_RegGenCint();
extern void G__cpp_setup_funcHyperonMC_RegGenCint();
extern void G__set_cpp_environmentHyperonMC_RegGenCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/HyDetectorConstruction.h"
#include "include/HyParticle.h"
#include "include/HyGeoParameters.h"
#include "include/HyMCApplication.h"
#include "include/HyMCStack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TClass;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TBuffer;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMemberInspector;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TObject;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TNamed;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TString;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TObjArray;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TRandom3;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMCProcess;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TVirtualMCApplication;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TParticle;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TVirtualMCStack;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TLorentzVector;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_HyGeoParameters;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_HyDetectorConstruction;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TFile;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TRef;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TRefArray;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_HyParticle;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_HyMCStack;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_dequelEHyParticlemUcOallocatorlEHyParticlemUgRsPgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_stacklEHyParticlemUcOdequelEHyParticlemUcOallocatorlEHyParticlemUgRsPgRsPgR;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_TH1F;
extern G__linked_taginfo G__HyperonMC_RegGenCintLN_HyMCApplication;

/* STUB derived class for protected member access */
